[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "processlargedatajava"
description = "This Java function takes a large JSON payload, calculates the distance between a supplied cordinate and the data, sorts it, and returns the nearest x results."
type = "function"